/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./../../components/ui/Card.vue')['default']
    CarteirasHeader: typeof import('./../../components/CarteirasHeader.vue')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./../../components/WalletCreateDialoag copy.vue')['default']
    Dashboard: typeof import('./../../components/layouts/dashboard/index.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Footer: typeof import('./../../components/ui/Footer.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingProvider: typeof import('./../../components/ui/LoadingProvider.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    TopNavbar: typeof import('./../../components/ui/TopNavbar.vue')['default']
    ValidateProvider: typeof import('./../../components/ui/ValidateProvider.vue')['default']
    WalletCreateDialoag: typeof import('./../../components/WalletCreateDialoag.vue')['default']
    WalletDeleteDialog: typeof import('./../../components/WalletDeleteDialog.vue')['default']
    WalletFilter: typeof import('./../../components/WalletFilter.vue')['default']
    WalletHeader: typeof import('./../../components/WalletHeader.vue')['default']
    WalletList: typeof import('./../../components/WalletList.vue')['default']
    WalletViewDialoag: typeof import('./../../components/WalletViewDialoag.vue')['default']
  }
}
